---
version: "3"
services:
  twspace-crawler:
    image: ghcr.io/hitomarukonpaku/twspace-crawler:latest
    container_name: twspace-crawler
    user: 1000:1000
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./.env:/app/.env
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
      - ./download:/app/download
