export const APP_CACHE_DIR = './.cache'
export const APP_DOWNLOAD_DIR = './download'
export const APP_USER_REFRESH_INTERVAL = 30000
export const APP_SPACE_ERROR_RETRY_INTERVAL = 10000
export const APP_PLAYLIST_REFRESH_INTERVAL = 10000
export const APP_PLAYLIST_CHUNK_VERIFY_MAX_RETRY = 20
