export const TWITTER_API_URL = 'https://api.twitter.com'
export const TWITTER_PUBLIC_AUTHORIZATION = 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA'
export const TWITTER_GUEST_TOKEN_RETRY_MS = 5000
export const TWITTER_GUEST_TOKEN_DURATION = 1800000
export const TWITTER_API_LIST_SIZE = 100
export const TWITTER_USER_FETCH_INTERVAL = 60000
